function commandList = eyeLinkDraw(self, command, details) %#ok<*CCAT>

    % If there's no Eyelink, stop right now.
    if ~self.eye.connected, return; end;
    
    % Handle optional argument
    if ~exist('details', 'var'), details = ''; end

    % Prepare commandList, which is useful for adding the commands
    % generated by this function to the commandBuffer.
    commandList = {};
        
    switch command
        case 'clear'
            % Clear the eye link display
            caseCommand = 'clear_screen 0';
            Eyelink('Command', caseCommand);
            commandList = {caseCommand commandList{:}};

        case 'buffer'
            % Draw the buffer, but copy buffer to commandList first
            commandList = self.eye.commandBuffer;
            
            % Iterate through command buffer and send each
            while numel(self.eye.commandBuffer) > 0
                Eyelink('Command', self.eye.commandBuffer{end});
                self.eye.commandBuffer = self.eye.commandBuffer(1:end-1);
            end
            self.eyeLinkCommandBuffer('clear');
          
            
        case 'fix'
            % Draw a cross indicating subject center
            caseCommand = sprintf('draw_cross %d %d 10', self.displayCenter);
            Eyelink('Command', caseCommand);
            commandList = {caseCommand commandList{:}}; 
            
            
        case 'rect'
            % Draw a rectangle
            caseCommand = sprintf('draw_box %d %d %d %d 15', details);
            Eyelink('Command', caseCommand);
            commandList = {caseCommand commandList{:}};
            
        case {'circ', 'circle'}
            % Draw an octagon to serve as a circle
            n = 8;
            
            % Pull info from details:
            r = details(1);
            
            if numel(details) >= 3
                cX = details(2);
                cY = details(3);
            else
                cX = self.displayCenter(1);
                cY = self.displayCenter(2);
            end
            
            % Start by generating coordinates for lines...
            a = tan(pi/n)*r;
            x = [r  a -a -r -r -a  a  r  r] + cX;
            y = [a  r  r  a -a -r -r -a  a] + cY;
            
            for cmd = 1:n
                caseCommand = sprintf('draw_line %d %d %d %d 10', ...
                                      [x(cmd) y(cmd) x(cmd+1) y(cmd+1)]);
                Eyelink('Command', caseCommand);
                commandList = {caseCommand commandList{:}};
            end
            
            
        case {'cross', 'cue'}
            % Draw a cross
            caseCommand = sprintf('draw_cross %d %d 10', details);
            Eyelink('Command', caseCommand);
            commandList = {caseCommand commandList{:}};
            
        otherwise
            % Otherwise pass the command through
            Eyelink('Command', command)
            commandList = {command commandList{:}};
    end

end