function config = default_config

    config = struct(                        ...
        'itiDuration',       2000,          ...
        'experimentName',    'experiment',  ...
        'subjectName',       'subject',     ...
        'osdHeight',         200,           ...
        'backgroundColor',   [0   0   0],   ...
        'osdBackgroundColor',[0   0   0],   ...
        'fixationPointColor',[255 255 255], ...
        'fixationWindowSize',4,             ...
        'calibrationColor',  [255 255 255], ...
        'calibrationSize',   1,             ...
        'calibrationWidth',  .5,            ...
        'calibrationEcc',    6,             ...
        'cueColor',          [255 255 255], ...
        'trackedEye',        'right',       ...
        'dataPath',          '.',           ...
        'fileName',          '',            ...
        'screen',            0,             ...
        'screenDistanceCm',  47,            ...
        'screenWidthCm',     37.4,          ...
        'screenHeightCm',    30,            ...
        'screenElevationCm', 61,            ... 
        'eyeElevationCm',    73,            ...
        'autoDrawEyeLink',   1,             ...
        'daqAdaptor',        'nidaq',       ...
        'daqID',             'Dev1');

end