function codes = default_codes

    codes = struct(                         ...
        'correct',           0,             ...
        'beginITI',          16,            ...
        'endITI',            17,            ...
        'beginTrial',        10,            ...
        'endTrial',          11,            ...
        'reward',            26,            ...
        'displayUpdate',     27,            ...
        'screenClear',       28);

end
