% Clear the screen
function clearScreen(self)
    % Clear the task portion of the display by drawing a rectangle
    Screen('FillRect',                  ...
           self.ptb.windowPtr,          ...
           self.config.backgroundColor, ...
           self.taskRect);
end